---
label: Project
hide_body: true
is_partial: false
fields:
- type: text
  name: title
  label: Title
  config:
    required: true
- type: textarea
  name: description
  label: Description
- type: image_gallery
  name: gallery_images
  label: Gallery Images
pages:
- src/content/projects/new-fashion.md
- src/content/projects/fahsion.md
