---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections: 
upload_dir: static/assets/media
public_path: "/media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: gatsby build
  publish_command: gatsby build
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.49
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.49
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  preview_docker_image: node:10
  mount_path: "/srv"
version: '0.49'
