---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: src/content/posts
  label: Pages
  create: documents
  match: "**/*"
  templates:
  - post
- type: directory
  path: src/content/projects
  label: Projects
  create: documents
  match: "*"
upload_dir: src/static/assets/media
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.51'
